name: github_repository_explorer
description: A GitHub Repository Explorer built with Flutter (Clean Architecture, BLoC, DI, Hive caching, pagination).
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  dio: ^5.9.0
  get_it: ^8.2.0
  injectable: ^2.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  url_launcher: ^6.3.2
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  connectivity_plus: ^6.1.5
  go_router: ^16.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  injectable_generator: ^2.8.1
  lints: ^6.0.0
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true
