name: Build & Release Web

on:
  push:
    tags:
      - 'v*'

jobs:
  build_release_web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.1'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web Release
        run: flutter build web --release

      - name: Zip Web Build
        run: |
          cd build/web
          zip -r ../web-release.zip .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Web Build
        uses: softprops/action-gh-release@v1
        with:
          files: build/web-release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
