name: Build & Release APK

on:
  push:
    tags:
      - 'v*'

jobs:
  build_release_apk:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.1'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 4️⃣ Build Release APK
      - name: Build Release APK
        run: flutter build apk --release

      # 5️⃣ Create GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}  # current pushed tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 6️⃣ Upload APK to Release
      - name: Upload APK to Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
