name: Build & Release iOS

on:
  push:
    tags:
      - 'v*'

jobs:
  build_release_ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.1'

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS Release
        run: flutter build ios --release --no-codesign

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload iOS Build
        uses: softprops/action-gh-release@v1
        with:
          files: build/ios/iphoneos/*.app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
